---
apiVersion: v1
kind: Service
metadata:
  name: swagger-ui
spec:
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: swagger-ui

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swagger-ui
  name: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
      - name: swagger-ui
        image: docker.io/swaggerapi/swagger-ui:v4.14.3
        env:
        - name: QUERY_CONFIG_ENABLED
          value: "true"
        volumeMounts:
        - name: swagger-ui-api
          mountPath: /usr/share/nginx/html/openapi
      volumes:
      - name: swagger-ui-api
        configMap:
          name: swagger-ui-api
